# Generated by Django 3.1.4 on 2020-12-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201220_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='nomeFantasia',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
