# Generated by Django 3.1.4 on 2020-12-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estabelecimento_nomefantasia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data',
            field=models.DateField(),
        ),
    ]
