# Generated by Django 3.1.4 on 2020-12-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201220_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientevacina',
            name='data',
            field=models.DateField(),
        ),
    ]
