# Generated by Django 3.1.4 on 2020-12-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201220_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='fila_chamada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
