# Generated by Django 3.1.4 on 2020-12-21 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201221_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacina',
            name='estoque',
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('estabelecimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estabelecimento')),
                ('vacina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vacina')),
            ],
        ),
    ]
